### ISSUE TITLE
Mentioned Tab Bugging out 

### ISSUE THREAD

**Issue by Jelexis** [TakosThings/Metro-for-Discord#149]
**Describe the bug**
The Mentioned tab when opening. is normal then suddenly bugs out instantly 
**Steps to reproduce**
When Opening the mentioned tab
**Screenshots**

![image](https://user-images.githubusercontent.com/34991429/79051456-0bbae800-7c39-11ea-8604-89a1a44e701e.png)

the tab is clipped to the side

**Comment by TakosThings** [comment]
Temporary fix: 

Remove lines 2870 and 2871
```CSS
.messagesPopoutWrap-1MQ1bW:not(.recentMentionsPopout-2fmau1) {
  right: -200px !important; }
```
