### ISSUE TITLE
Layout Issue on Ubuntu 20.04

### ISSUE THREAD

**Issue by noahjsmyth** [TakosThings/Metro-for-Discord#179]
**Describe the bug**
Message box does not reach the bottom of the app

**Steps to reproduce**
Install theme on Ubuntu 20.04

**Screenshots**
![Screenshot from 2020-08-17 23-51-46](https://user-images.githubusercontent.com/38191751/90451841-a7c39700-e0e4-11ea-925e-f4146a51f04f.png)

**Comment by TakosThings** [comment]
This is likely due to the native titlebars

Changing the below *might* fix it. Though this needs to be re-applied every update.

**From**
```CSS
.base-3dtUhz{
    height: calc(100vh - 32px);
}
```
**to**
```CSS
.base-3dtUhz{
    height: 100vh;
}
```
