### ISSUE TITLE
Games tab fixed when?

### ISSUE THREAD

**Issue by iKatt** [TakosThings/Metro-for-Discord#47]
Been like this for a few patches, surely you've noticed
https://puu.sh/B3Loi/b26314f8f0.mp4

**Comment by TakosThings** [comment]
I don't have this issue. Try adding the below CSS and see if it fixes it;
```CSS
.private-channels .channel.btn-friends:nth-of-type(1){
    top: 0;
    left: 0;
}
```
