### ISSUE TITLE
Logo is overlapping  

### ISSUE THREAD

**Issue by trollmad3** [TakosThings/Metro-for-Discord#74]
![discord_2019-02-22_11-52-42](https://user-images.githubusercontent.com/7843719/53260947-6b9eaa00-3698-11e9-99d1-cd83afad75ef.png)

There was a new discord update and now one of the logos is overlapping the add server. The new feature is called 'Discovery Server'

**Comment by TakosThings** [comment]
Add the following CSS to your file/custom CSS for now
```CSS
.guildsDiscover-oiBX_l{
    display: none;
}
```
