### ISSUE TITLE
[Feedback] Home Button

### ISSUE THREAD

**Issue by bmijnendonckx** [TakosThings/Metro-for-Discord#81]
Hey I've been using this theme for quite a while now and I absolutely love it, even the recent restyling. But there's 1 thing that bothers me and maybe some others too. The home button.
My most used servers are on the bottom of the list of servers, and while typing I do realize I could just have my own server at the top, I find myself scrolling up and down a lot. I have 30-40 servers so that's quite a lot.

So I've changed the home button to be always on top for me. I thought it might be nice to have this optional in the theme for those who'd like it

```css
.container-1ETFDs {
  position: absolute;
  z-index: 1;
  background-color: #171717;
}

.container-2td-dC:first-child, :not(.container-2td-dC) + .container-2td-dC {
  margin-top: 48px;
}
```

using BetterDiscord if that matters.

**Comment by bmijnendonckx** [comment]
```css
.container-1ETFDs {
  position: absolute;
  z-index: 1;
  top: 0;
  background-color: #171717;
}

.scroller-2FKFPG.firefoxFixScrollFlex-cnI2ix.systemPad-3UxEGl.scroller-2TZvBN {
  margin-top: 48px;
}
```

rewrote it cause the dragging server was buggy with the above method
